
modLoader="javafml"

loaderVersion="[32,)"

license="All rights reserved"

#issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="bundleditems"

version="1.4.2"

displayName="Bundled Items"

#updateJSONURL="http://myurl.me/"

displayURL="https://www.curseforge.com/minecraft/mc-mods/bundled-items"

logoFile="bundleditems.png"

credits="idrae_ (Item Decrafting/French Translation), Mr. Pineapple (Fabric Port), Is (Artist)"

authors="puxped (Creator), Viper_ (Artist)"

description='''
A Mod that lets you bundle your items, so they take up less valuable space in your inventory.
'''

[[dependencies.bundleditems]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bundleditems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.16.5]"
    ordering="NONE"
    side="BOTH"
